Api/urls.py
from django.urls import include, path
from rest_framework import routers
from Api import views
from rest_framework.urlpatterns import format_suffix_patterns



urlpatterns = [

    #Home
    path('', views.apiOverview, name="api-overview"),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Category API    
    path('category-list/', views.CategoryList, name="api_category_list"),
    path('category-create/', views.CategoryCreate, name="api_category_create"),
    path('category-detail/<int:pk>/', views.CategoryDetail, name="api_category_detail"),
    path('category-delete/<int:pk>/', views.CategoryDelete, name="api_category_delete"),
    
    # Book API    
    path('book-list/', views.BookList, name="api_book_list"),
    path('book-create/', views.BookCreate, name="api_book_create"),
    path('book-detail/<int:pk>/', views.BookDetail, name="api_book_detail"),
    path('book-update/<int:pk>/', views.BookUpdate, name="api_book_update"),
    path('book-delete/<int:pk>/', views.BookDelete, name="api_book_delete"),

    # Publisher API    
    path('publisher-list/', views.PublisherList, name="api_publisher_list"),
    path('publisher-create/', views.PublisherCreate, name="api_publisher_create"),
    path('publisher-update/<int:pk>/', views.PublisherUpdate, name="api_publisher_update"),
    path('publisher-delete/<int:pk>/', views.PublisherDelete, name="api_publisher_delete"),

    # Member API
    path('members/', views.MemberList.as_view()),
    path('members/<int:pk>', views.MemberDetail.as_view()),
]


urlpatterns = format_suffix_patterns(urlpatterns)

book/urls.py
from django.contrib import admin
from django.urls import path, include  # add this
from .views import HomeView,BookListView,BookCreateView,BookDeleteView,BookDetailView,BookUpdateView
from .views import CategoryListView,CategoryCreateView,CategoryDeleteView
from .views import PublisherListView,PublisherCreateView,PublisherDeleteView,PublisherUpdateView
from .views import ActivityListView,ActivityDeleteView
from .views import MemberCreateView,MemberUpdateView,MemberDeleteView,MemberListView,MemberDetailView
from .views import ProfileDetailView,ProfileCreateView,ProfileUpdateView
from django.conf import settings
from django.conf.urls.static import static
from .views import BorrowRecordListView,BorrowRecordCreateView,BorrowRecordDeleteView,BorrowRecordDetailView,auto_member,auto_book,BorrowRecordClose
from .views import DataCenterView,download_data
from .views import ChartView,global_serach,EmployeeView,EmployeeDetailView,EmployeeUpdate,NoticeListView,NoticeUpdateView

urlpatterns = [

    # 主页
    path("",HomeView.as_view(), name='home'),
    # 物品
    path('book-list',BookListView.as_view(),name="book_list"),
    path('book-create',BookCreateView.as_view(),name="book_create"),
    path('book-update/<int:pk>/',BookUpdateView.as_view(),name="book_update"),
    path('book-delete/<int:pk>/',BookDeleteView.as_view(),name="book_delete"),
    path('book-detail/<int:pk>/',BookDetailView.as_view(),name="book_detail"),

    # 分类
    path('category-list',CategoryListView.as_view(),name="category_list"),
    path('category-create',CategoryCreateView.as_view(),name="category_create"),  
    path('category-delete/<int:pk>/',CategoryDeleteView.as_view(),name="category_delete"), 

    # 提供者
    path('publisher-list',PublisherListView.as_view(),name="publisher_list"),
    path('publisher-create',PublisherCreateView.as_view(),name="publisher_create"),  
    path('publisher-delete/<int:pk>/',PublisherDeleteView.as_view(),name="publisher_delete"), 
    path('publisher-update/<int:pk>/',PublisherUpdateView.as_view(),name="publisher_update"),

    # 管理员操作
    path('user-activity-list',ActivityListView.as_view(),name="user_activity_list"),
    path('user-activity-list/<int:pk>/',ActivityDeleteView.as_view(),name="user_activity_delete"),

    # 用户
    path('member-list',MemberListView.as_view(),name="member_list"),
    path('member-create',MemberCreateView.as_view(),name="member_create"),  
    path('member-delete/<int:pk>/',MemberDeleteView.as_view(),name="member_delete"), 
    path('member-update/<int:pk>/',MemberUpdateView.as_view(),name="member_update"),
    path('member-detail/<int:pk>/',MemberDetailView.as_view(),name="member_detail"),

    # 管理员个人中心
    path('user/profile-create/',ProfileCreateView.as_view(),name="profile_create"),
    path('user/<int:pk>/profile/',ProfileDetailView.as_view(),name="profile_detail"),
    path('user/<int:pk>/profile-update/',ProfileUpdateView.as_view(),name="profile_update"),


    # 租借记录
    path('record-create/',BorrowRecordCreateView.as_view(),name="record_create"),
    # path('record-create/',record_create,name="record_create"),

    path('record-create-autocomplete-member-name/',auto_member,name="auto_member_name"),
    path('record-create-autocomplete-book-name/',auto_book,name="auto_book_name"),
    path('record-list/',BorrowRecordListView.as_view(),name="record_list"),
    path('record-detail/<int:pk>/',BorrowRecordDetailView.as_view(),name="record_detail"),
    path('record-delete/<int:pk>/',BorrowRecordDeleteView.as_view(),name="record_delete"),
    path('record-close/<int:pk>/',BorrowRecordClose.as_view(),name="record_close"),

    # Data center
    path('data-center/',DataCenterView.as_view(),name="data_center"),
    path('data-download/<str:model_name>/',download_data,name="data_download"),

    # Chart
    path('charts/',ChartView.as_view(),name="chart"),

    # 全局搜索
    path('global-search/',global_serach,name="global_search"),

    # Employee
    path('employees/',EmployeeView.as_view(),name="employees_list"),
    path('employees-detail/<int:pk>',EmployeeDetailView.as_view(),name="employees_detail"),
    path('employees-update/<int:pk>',EmployeeUpdate,name='employee_update'),

    # Notice
    path('notice-list/', NoticeListView.as_view(), name='notice_list'),
    path('notice-update/', NoticeUpdateView.as_view(), name='notice_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include  # add this
# from django.conf.urls import handler400, handler403, handler404, handler500
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),          
    path("auth/", include("authentication.urls")), # Auth routes - login / register
    path("", include("book.urls")),
    path('api/', include('Api.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = 'book.views.bad_request'
handler403 = 'book.views.permission_denied'
handler404 = 'book.views.page_not_found'
handler500 = 'book.views.server_error'

book/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
# from phonenumber_field.modelfields import PhoneNumberField
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import uuid
from PIL import Image


BOOK_STATUS =(
    (0, "借出"),
    (1, "在库里"),
)

FLOOR =(
    (1, "一楼"),
    (2, "二楼"),
    (3, "三楼"),
)

OPERATION_TYPE =(
    ("success", "Create"),
    ("warning","Update"),
    ("danger","Delete"),
    ("info",'Close')
)

GENDER=(
    ("m","男"),
    ("f","女"),
)

BORROW_RECORD_STATUS=(
    (0,'正在借'),
    (1,'已入库')
)

class Category(models.Model):
    
    name = models.CharField(verbose_name='分类名',max_length=50, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name
    #增删改查后返回
    def get_absolute_url(self): 
        return reverse('category_list')

    # class Meta:
    #     db_table='category'

class Publisher(models.Model):
    
    name = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    contact = models.EmailField(max_length=50,blank=True)
    # created_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_by=models.CharField(max_length=20,default='yaozeliang')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self): 
        return reverse('publisher_list')

class Book(models.Model):
    author = models.CharField(verbose_name="提供者",max_length=20)
    title = models.CharField(verbose_name='物品名称',max_length=100)
    description = models.TextField(verbose_name='物品描述')
    created_at = models.DateTimeField('Created Time',default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    total_borrow_times = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(verbose_name='数量',default=10)
    category = models.ForeignKey(
        Category,
        verbose_name='分类',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='category'
    )

    publisher=models.ForeignKey(
        Publisher,
        verbose_name='提供者',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='publisher'
    )

    status=models.IntegerField(choices=BOOK_STATUS,default=1)
    floor_number=models.IntegerField(verbose_name='楼层编号',choices=FLOOR,default=1)
    bookshelf_number=models.CharField(verbose_name='物品架编号',max_length=10,default='0001')
    updated_by=models.CharField(max_length=20,default='yaozeliang')

    def get_absolute_url(self): 
        return reverse('book_list')
    
    def __str__(self):
        return self.title

class UserActivity(models.Model):
    created_by=models.CharField(default="",max_length=20)
    created_at =models.DateTimeField(auto_now_add=True)
    operation_type=models.CharField(choices=OPERATION_TYPE,default="success",max_length=20)
    target_model = models.CharField(default="",max_length=20)
    detail = models.CharField(default="",max_length=50)

    def get_absolute_url(self): 
        return reverse('user_activity_list')

class Member(models.Model):
    name = models.CharField(verbose_name='会员名',max_length=50, blank=False)
    age = models.PositiveIntegerField(verbose_name='年龄',default=20)
    gender = models.CharField(verbose_name='性别',max_length=10,choices=GENDER,default='m')

    city = models.CharField(verbose_name='城市',max_length=20, blank=False)
    email = models.EmailField(max_length=50,blank=True)
    phone_number = models.CharField(verbose_name='电话号码',max_length=30,blank=False)

    created_at= models.DateTimeField(default=timezone.now)
    created_by = models.CharField(max_length=20,default="")
    updated_by = models.CharField(max_length=20,default="")
    updated_at = models.DateTimeField(auto_now=True)

    card_id = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    card_number = models.CharField(max_length=8,default="")
    expired_at = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self): 
        return reverse('member_list')
    # 练习save方法
    def save(self, *args, **kwargs):
        self.card_number = str(self.card_id)[:8]
        self.expired_at = timezone.now()+relativedelta(years=1)
        return super(Member, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


# 管理员个人中心
class Profile(models.Model):
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    bio = models.TextField('介绍')
    profile_pic = models.ImageField('个人头像图片',upload_to="profile/%Y%m%d/", blank=True,null=True)
    phone_number = models.CharField('电话号码',max_length=30,blank=True)
    email = models.EmailField(max_length=50,blank=True)

    def save(self, *args, **kwargs):
        # 调用原有的 save() 的功能
        profile = super(Profile, self).save(*args, **kwargs)

        # 固定宽度缩放图片大小
        if self.profile_pic and not kwargs.get('update_fields'):
            image = Image.open(self.profile_pic)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.profile_pic.path)

        return profile

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self): 
        return reverse('home')


# 租借记录

class BorrowRecord(models.Model):
    borrower = models.CharField(blank=False,max_length=20)
    borrower_card = models.CharField(max_length=8,blank=True)
    borrower_email = models.EmailField(max_length=50,blank=True)
    borrower_phone_number  = models.CharField(max_length=30,blank=True)
    book = models.CharField(blank=False,max_length=20)
    quantity = models.PositiveIntegerField('数量',default=1)

    start_day = models.DateTimeField('租借开始时间',default=timezone.now)
    end_day = models.DateTimeField('归还时间',default=timezone.now()+timedelta(days=7))
    periode = models.PositiveIntegerField(default=0)

    open_or_close = models.IntegerField(choices=BORROW_RECORD_STATUS,default=0)
    delay_days = models.IntegerField(default=0)
    final_status = models.CharField(max_length=10,default="Unknown")

    created_at= models.DateTimeField(default=timezone.now)
    created_by = models.CharField(max_length=20,blank=True)
    closed_by = models.CharField(max_length=20,default="")
    closed_at = models.DateTimeField(auto_now=True)

    @property
    def return_status(self):
        if self.final_status!="Unknown":
            return self.final_status
        elif self.end_day.replace(tzinfo=None) > datetime.now()-timedelta(hours=24):
            return 'On time'
        else:
            return 'Delayed'

    @property
    def get_delay_number_days(self):
        
        if self.delay_days!=0:
            return self.delay_days
        elif self.return_status=='Delayed':
            return (datetime.now()-self.end_day.replace(tzinfo=None)).days
        else:
            return 0


    def get_absolute_url(self): 
        return reverse('record_list')

    def __str__(self):
        return self.borrower+"->"+self.book
    
    def save(self, *args, **kwargs):
        # profile = super(Profile, self).save(*args, **kwargs)
        self.periode =(self.end_day - self.start_day).days+1
        return super(BorrowRecord, self).save(*args, **kwargs)

book/forms.py
from django import forms
from .models import Book,Publisher,Member,Profile,BorrowRecord
from django.contrib.admin.widgets import AutocompleteSelect
from django.contrib import admin
from django.urls import reverse
from flatpickr import DatePickerInput, TimePickerInput, DateTimePickerInput


class BookCreateEditForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('author',
                  'title',
                  'description',
                  'quantity', 
                  'category',
                  'publisher',
                  'floor_number',
                  "bookshelf_number")


class PubCreateEditForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = ('name',
                  'city',
                  'contact',
                  )
        # fields="__all__"

class MemberCreateEditForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ('name',
                  'gender',
                  'age',
                  'email',
                  'city', 
                  'phone_number',)


class ProfileForm(forms.ModelForm):

    
    class Meta:
        model = Profile
        fields = ( 'profile_pic',
                  'bio', 
                  'phone_number',
                  'email')


class BorrowRecordCreateForm(forms.ModelForm):

    borrower = forms.CharField(label='租借者',
                    widget=forms.TextInput(attrs={'placeholder': '搜索租借用户...'}))
    
    book = forms.CharField(help_text='输入想搜索的物品名称')

    class Meta:
        model = BorrowRecord
        fields=['borrower','book','quantity','start_day','end_day']
        # widgets = {
        #     'start_day': DatePickerInput().start_of('event datetime'),
        #     'end_day': DatePickerInput().end_of('event datetime'),
        # }
        widgets = {
            'start_day': DatePickerInput(options = {  "dateFormat": "Y-m-d", }),
            'end_day': DatePickerInput(options = {  "dateFormat": "Y-m-d", }),
        }
        # widgets = {'start_day': forms.DateTimeInput(attrs={'class': 'datepicker'}),
        #            'end_day': forms.DateTimeInput(attrs={'class': 'datepicker'})}


        # widgets = {
        #     'start_day': DateTimePickerInput(format='%Y-%m-%d'),
        #     'end_day': DateTimePickerInput(format='%Y-%m-%d'),
        # }


# from  django.forms.widgets import SelectDateWidget

# class BorrowRecordCreateForm(forms.ModelForm):

#     def __init__(self, *args, **kwargs):
#         super(BorrowRecordCreateForm, self).__init__(*args, **kwargs)
#         #Change date field's widget here
#         self.fields['start_day'].widget = SelectDateWidget()
#         self.fields['end_day'].widget = SelectDateWidget()

#     class Meta:
#         model = BorrowRecord
#         fields=['borrower','book','quantity','start_day','end_day']

templates/book/book_create.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block title %} 管理 {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
{% endblock stylesheets %}
{% block content %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">租借管理</h5>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <br>
        <!-- [ breadcrumb ] end -->
        <div class="main-body">
            <div class="page-wrapper">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>增加新的租借物品</h5>
                            </div>
                            <div class="card-block table-border-style">
                                <!-- <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% for field in form %}
                                    <div class="form-group">
                                        <label>{{ field.label }}</label>
                                        {% if field.field.widget.input_type != "select" %}
                                        <input type="{{ field.field.widget.input_type }}" name={{ field.name }} id="{{ field.name }}" class="form-control">
                                        {% endif %}



                                        {% if field.field.widget.input_type == "select" %}
                                        <select name={{ field.name }} id="{{ field.name }}" class="form-control">
                                            {% for id,value in field.field.choices %}
                                                <option value="{{ id }}">{{ value }}</option>
                                            {% endfor %}
                                        </select>
                                        {% endif %}

                                        {% if field.errors %}
                                        <div class="alert alert-danger" style="margin:10px">
                                            {{ field.errors }}
                                        </div>
                                        {% endif %}
                                    </div>
                                    {% endfor %}

                                    <button type="submit" class="btn btn-primary btn-block">Add New Book</button>
                                </form> -->

                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}

                                    {{ form|crispy }}


                                    <button type="submit" class="btn btn-primary">添加新的物品</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/book/member_detail.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% block title %} 管理{% endblock %}

{% block stylesheets %}
<!-- <link rel="stylesheet" href="/static/assets/css/card.css"> -->

{% endblock stylesheets %}

{% block content %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">用户管理</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <!-- [ breadcrumb ] end -->
        <div class="main-body">
            <div class="page-wrapper">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-header">
                                <h5><i class="fas fa-user-tie"></i> 用户信息  </h5>
                            </div>

                            <div class="card-block">
                                <div class="col-md-12">
                                    <h5 class="mt-2">{{member.name}}</h5>
                                    <hr>
                                    <div class="row">
                                        <div class="col-md-3 col-sm-12">
                                            <ul class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                                                <li><a class="nav-link text-left active" id="basic-info-tab" data-toggle="pill" href="#basic-info" role="tab" aria-controls="basic-info" aria-selected="true">用户概述</a></li>
                                                <!-- <li><a class="nav-link text-left" id="contact-tab" data-toggle="pill" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contact</a></li> -->
                                                <li><a class="nav-link text-left" id="card-tab" data-toggle="pill" href="#card" role="tab" aria-controls="card" aria-selected="false">卡号</a></li>
                                                <li><a class="nav-link text-left" id="audit-trail-tab-1" data-toggle="pill" href="#audit-trail" role="tab" aria-controls="audit-trail" aria-selected="false">创建时间信息</a></li>
                                                <li><a class="nav-link text-left" id="audit-trail-tab-2" data-toggle="pill" href="#borrow-record" role="tab" aria-controls="borrow-record" aria-selected="false">租借记录</a></li>

                                            </ul>
                                        </div>
                                        <div class="col-md-9 col-sm-12">
                                            <div class="tab-content" id="v-pills-tabContent">
                                                <div class="tab-pane fade show active" id="basic-info" role="tabpanel">
                                                    <div class='row'>
                                                        <div class='col-6'>
                                                            <p>姓名: {{member.name}} </p>
                                                            <p>性别: {{member.get_gender_display}} </p>
                                                            <p>年龄: {{member.age}} </p>
                                                            <p>城市: {{member.city}} </p>
                                                        </div>
                                                        <div class='col-6'>
                                                            <p>电话号码: {{member.phone_number}} </p>
                                                            <p>Email: {{member.email}} </p>
                                                        </div>
                                                    </div>                                                
                                                </div>
                                                <!-- <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                                                    <p class="mb-0">Culpa dolor voluptate do laboris laboris irure reprehenderit id incididunt duis pariatur mollit aute magna pariatur consectetur. Eu veniam duis non ut dolor deserunt commodo et minim in quis laboris ipsum velit id veniam. Quis ut consectetur adipisicing officia excepteur non sit. Ut et elit aliquip labore Lorem enim eu. Ullamco mollit occaecat dolore ipsum id officia mollit qui esse anim eiusmod do sint minim consectetur qui.</p>
                                                </div> -->

                                                <div class="tab-pane fade" id="card" role="tabpanel" aria-labelledby="card-tab">
                                                    <p>卡 ID: {{member.card_id}}</p>
                                                    <p>卡号: {{member.card_number}}</p>
                                                    <p>创建时间: {{member.created_at| date:"Y/m"}} </p>
                                                    <p>过期时间: {{member.expired_at| date:"Y/m"}}</p>
                                                
                                                </div>
                                                <div class="tab-pane fade" id="audit-trail" role="tabpanel" aria-labelledby="audit-trail-tab">
                                                    <p>创建时间 : {{member.created_at| date:"Y-m-d H:i"}} </p>
                                                    <p>创建管理员 : {{member.created_by}} </p>
                                                    <br>
                                                    <p>更新时间 : {{member.updated_at | date:"Y-m-d H:i"}}</p>
                                                    <p>更新管理员 : {{member.updated_by}} </p>
                                                </div>

                                                <div class="tab-pane fade" id="borrow-record" role="tabpanel" aria-labelledby="audit-trail-tab">
                                                    {% if related_records %}
                                                    <table class="table table-sm">
                                                       <thead>
                                                         <tr>
                                                           <th scope="col">租借</th>
                                                           <th scope="col">卡</th>
                                                           <th scope="col">物品名</th>
                                                           <th scope="col">开始时间 - 归还截止时间</th>
                                                           <th scope="col">物品状态</th>
                                                           <th scope="col">归还时间</th>
                                                           <th scope="col">#</th>
                                                         </tr>
                                                       </thead>
                                                       <tbody>
                                                        
                                                        {% for record in related_records %}
                                                        <tr>
                                                            <td>{{record.borrower}} </td>
                                                            <td>{{record.borrower_card}}</td>
                                                            <td>{{record.book}}</td>
                                                            <td>{{record.start_day | date:"Y/m/d"}} - {{record.end_day | date:"Y/m/d"}}</td>
                                                            <td>{{record.get_open_or_close_display}}</td>
                                                            <td>{{record.closed_at | date:"Y/m/d"}}</td>
                                                            {% if record.final_status == "Delayed" %}
                                                                <td>{{record.final_status}}, {{record.delay_days}} days</td>
                                                            {% else %}
                                                                <td>{{record.final_status}}</td>
                                                            {% endif %}
                                                          </tr>
                                      
                                                       {% endfor %}
                                                       {% else %}
                                                       <h4 class="text-center">没有租借记录</h4>
                                                       {% endif  %}
                                                       </tbody>
                                                     </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            

                        </div>
                        <a href="{% url 'member_list' %}" class='btn btn-dark'>返回用户列表</a>
                        <a href="{% url 'member_update' member.pk %}" class='btn btn-dark'>更新</a>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}