Api/urls.py
from django.urls import include, path
from rest_framework import routers
from Api import views
from rest_framework.urlpatterns import format_suffix_patterns



urlpatterns = [

    #Home
    path('', views.apiOverview, name="api-overview"),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Category API    
    path('category-list/', views.CategoryList, name="api_category_list"),
    path('category-create/', views.CategoryCreate, name="api_category_create"),
    path('category-detail/<int:pk>/', views.CategoryDetail, name="api_category_detail"),
    path('category-delete/<int:pk>/', views.CategoryDelete, name="api_category_delete"),
    
    # Book API    
    path('book-list/', views.BookList, name="api_book_list"),
    path('book-create/', views.BookCreate, name="api_book_create"),
    path('book-detail/<int:pk>/', views.BookDetail, name="api_book_detail"),
    path('book-update/<int:pk>/', views.BookUpdate, name="api_book_update"),
    path('book-delete/<int:pk>/', views.BookDelete, name="api_book_delete"),

    # Publisher API    
    path('publisher-list/', views.PublisherList, name="api_publisher_list"),
    path('publisher-create/', views.PublisherCreate, name="api_publisher_create"),
    path('publisher-update/<int:pk>/', views.PublisherUpdate, name="api_publisher_update"),
    path('publisher-delete/<int:pk>/', views.PublisherDelete, name="api_publisher_delete"),

    # Member API
    path('members/', views.MemberList.as_view()),
    path('members/<int:pk>', views.MemberDetail.as_view()),
]


urlpatterns = format_suffix_patterns(urlpatterns)

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include  # add this
# from django.conf.urls import handler400, handler403, handler404, handler500
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),          
    path("auth/", include("authentication.urls")), # Auth routes - login / register
    path("", include("book.urls")),
    path('api/', include('Api.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = 'book.views.bad_request'
handler403 = 'book.views.permission_denied'
handler404 = 'book.views.page_not_found'
handler500 = 'book.views.server_error'

book/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
# from phonenumber_field.modelfields import PhoneNumberField
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import uuid
from PIL import Image


BOOK_STATUS =(
    (0, "借出"),
    (1, "在库里"),
)

FLOOR =(
    (1, "一楼"),
    (2, "二楼"),
    (3, "三楼"),
)

OPERATION_TYPE =(
    ("success", "Create"),
    ("warning","Update"),
    ("danger","Delete"),
    ("info",'Close')
)

GENDER=(
    ("m","男"),
    ("f","女"),
)

BORROW_RECORD_STATUS=(
    (0,'正在借'),
    (1,'已入库')
)

class Category(models.Model):
    
    name = models.CharField(verbose_name='分类名',max_length=50, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name
    #增删改查后返回
    def get_absolute_url(self): 
        return reverse('category_list')

    # class Meta:
    #     db_table='category'

class Publisher(models.Model):
    
    name = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    contact = models.EmailField(max_length=50,blank=True)
    # created_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_by=models.CharField(max_length=20,default='yaozeliang')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self): 
        return reverse('publisher_list')

class Book(models.Model):
    author = models.CharField(verbose_name="提供者",max_length=20)
    title = models.CharField(verbose_name='物品名称',max_length=100)
    description = models.TextField(verbose_name='物品描述')
    created_at = models.DateTimeField('Created Time',default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    total_borrow_times = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(verbose_name='数量',default=10)
    category = models.ForeignKey(
        Category,
        verbose_name='分类',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='category'
    )

    publisher=models.ForeignKey(
        Publisher,
        verbose_name='提供者',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='publisher'
    )

    status=models.IntegerField(choices=BOOK_STATUS,default=1)
    floor_number=models.IntegerField(verbose_name='楼层编号',choices=FLOOR,default=1)
    bookshelf_number=models.CharField(verbose_name='物品架编号',max_length=10,default='0001')
    updated_by=models.CharField(max_length=20,default='yaozeliang')

    def get_absolute_url(self): 
        return reverse('book_list')
    
    def __str__(self):
        return self.title

class UserActivity(models.Model):
    created_by=models.CharField(default="",max_length=20)
    created_at =models.DateTimeField(auto_now_add=True)
    operation_type=models.CharField(choices=OPERATION_TYPE,default="success",max_length=20)
    target_model = models.CharField(default="",max_length=20)
    detail = models.CharField(default="",max_length=50)

    def get_absolute_url(self): 
        return reverse('user_activity_list')

class Member(models.Model):
    name = models.CharField(verbose_name='会员名',max_length=50, blank=False)
    age = models.PositiveIntegerField(verbose_name='年龄',default=20)
    gender = models.CharField(verbose_name='性别',max_length=10,choices=GENDER,default='m')

    city = models.CharField(verbose_name='城市',max_length=20, blank=False)
    email = models.EmailField(max_length=50,blank=True)
    phone_number = models.CharField(verbose_name='电话号码',max_length=30,blank=False)

    created_at= models.DateTimeField(default=timezone.now)
    created_by = models.CharField(max_length=20,default="")
    updated_by = models.CharField(max_length=20,default="")
    updated_at = models.DateTimeField(auto_now=True)

    card_id = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    card_number = models.CharField(max_length=8,default="")
    expired_at = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self): 
        return reverse('member_list')
    # 练习save方法
    def save(self, *args, **kwargs):
        self.card_number = str(self.card_id)[:8]
        self.expired_at = timezone.now()+relativedelta(years=1)
        return super(Member, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


# 管理员个人中心
class Profile(models.Model):
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    bio = models.TextField('介绍')
    profile_pic = models.ImageField('个人头像图片',upload_to="profile/%Y%m%d/", blank=True,null=True)
    phone_number = models.CharField('电话号码',max_length=30,blank=True)
    email = models.EmailField(max_length=50,blank=True)

    def save(self, *args, **kwargs):
        # 调用原有的 save() 的功能
        profile = super(Profile, self).save(*args, **kwargs)

        # 固定宽度缩放图片大小
        if self.profile_pic and not kwargs.get('update_fields'):
            image = Image.open(self.profile_pic)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.profile_pic.path)

        return profile

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self): 
        return reverse('home')


# 租借记录

class BorrowRecord(models.Model):
    borrower = models.CharField(blank=False,max_length=20)
    borrower_card = models.CharField(max_length=8,blank=True)
    borrower_email = models.EmailField(max_length=50,blank=True)
    borrower_phone_number  = models.CharField(max_length=30,blank=True)
    book = models.CharField(blank=False,max_length=20)
    quantity = models.PositiveIntegerField('数量',default=1)

    start_day = models.DateTimeField('租借开始时间',default=timezone.now)
    end_day = models.DateTimeField('归还时间',default=timezone.now()+timedelta(days=7))
    periode = models.PositiveIntegerField(default=0)

    open_or_close = models.IntegerField(choices=BORROW_RECORD_STATUS,default=0)
    delay_days = models.IntegerField(default=0)
    final_status = models.CharField(max_length=10,default="Unknown")

    created_at= models.DateTimeField(default=timezone.now)
    created_by = models.CharField(max_length=20,blank=True)
    closed_by = models.CharField(max_length=20,default="")
    closed_at = models.DateTimeField(auto_now=True)

    @property
    def return_status(self):
        if self.final_status!="Unknown":
            return self.final_status
        elif self.end_day.replace(tzinfo=None) > datetime.now()-timedelta(hours=24):
            return 'On time'
        else:
            return 'Delayed'

    @property
    def get_delay_number_days(self):
        
        if self.delay_days!=0:
            return self.delay_days
        elif self.return_status=='Delayed':
            return (datetime.now()-self.end_day.replace(tzinfo=None)).days
        else:
            return 0


    def get_absolute_url(self): 
        return reverse('record_list')

    def __str__(self):
        return self.borrower+"->"+self.book
    
    def save(self, *args, **kwargs):
        # profile = super(Profile, self).save(*args, **kwargs)
        self.periode =(self.end_day - self.start_day).days+1
        return super(BorrowRecord, self).save(*args, **kwargs)

book/forms.py
from django import forms
from .models import Book,Publisher,Member,Profile,BorrowRecord
from django.contrib.admin.widgets import AutocompleteSelect
from django.contrib import admin
from django.urls import reverse
from flatpickr import DatePickerInput, TimePickerInput, DateTimePickerInput


class BookCreateEditForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('author',
                  'title',
                  'description',
                  'quantity', 
                  'category',
                  'publisher',
                  'floor_number',
                  "bookshelf_number")


class PubCreateEditForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = ('name',
                  'city',
                  'contact',
                  )
        # fields="__all__"

class MemberCreateEditForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ('name',
                  'gender',
                  'age',
                  'email',
                  'city', 
                  'phone_number',)


class ProfileForm(forms.ModelForm):

    
    class Meta:
        model = Profile
        fields = ( 'profile_pic',
                  'bio', 
                  'phone_number',
                  'email')


class BorrowRecordCreateForm(forms.ModelForm):

    borrower = forms.CharField(label='租借者',
                    widget=forms.TextInput(attrs={'placeholder': '搜索租借用户...'}))
    
    book = forms.CharField(help_text='输入想搜索的物品名称')

    class Meta:
        model = BorrowRecord
        fields=['borrower','book','quantity','start_day','end_day']
        # widgets = {
        #     'start_day': DatePickerInput().start_of('event datetime'),
        #     'end_day': DatePickerInput().end_of('event datetime'),
        # }
        widgets = {
            'start_day': DatePickerInput(options = {  "dateFormat": "Y-m-d", }),
            'end_day': DatePickerInput(options = {  "dateFormat": "Y-m-d", }),
        }
        # widgets = {'start_day': forms.DateTimeInput(attrs={'class': 'datepicker'}),
        #            'end_day': forms.DateTimeInput(attrs={'class': 'datepicker'})}


        # widgets = {
        #     'start_day': DateTimePickerInput(format='%Y-%m-%d'),
        #     'end_day': DateTimePickerInput(format='%Y-%m-%d'),
        # }


# from  django.forms.widgets import SelectDateWidget

# class BorrowRecordCreateForm(forms.ModelForm):

#     def __init__(self, *args, **kwargs):
#         super(BorrowRecordCreateForm, self).__init__(*args, **kwargs)
#         #Change date field's widget here
#         self.fields['start_day'].widget = SelectDateWidget()
#         self.fields['end_day'].widget = SelectDateWidget()

#     class Meta:
#         model = BorrowRecord
#         fields=['borrower','book','quantity','start_day','end_day']

templates/borrow_records/create.html
{% extends "layouts/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} 租借记录 {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'assets/css/jquery-ui.min.css'%}">
<link rel="stylesheet" href="{% static 'assets/css/jquery.datetimepicker.css'%}">
{% endblock stylesheets %}
{% block content %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="main-body">
            <div class="page-wrapper">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>借取物品</h5>
                            </div>
                            <div class="card-block table-border-style">
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                   {{form | crispy}}
                                   {{form.media}}
                                    <button type="submit" class="btn btn-success">添加</button>
                                    <a href="{% url 'record_list' %} " class="btn btn-secondary">取消</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="{% static 'assets/plugins/jquery/js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'assets/plugins/jquery/js/jquery-ui.min.js' %}"></script>
<script src="{% static 'assets/plugins/jquery/js/jquery.datetimepicker.js' %}"></script>

<script>
$( function() {
$( "#id_borrower" ).autocomplete({
  source: "{% url 'auto_member_name' %}",
});

$( "#id_book" ).autocomplete({
  source: "{% url 'auto_book_name' %}",
});

// $("#id_start_day").datetimepicker( {
//     //    format:'Y-m-d H:i',
//     // dateFormat: "yy-mm-dd H:i:ss"
    
//   });

//  $("#id_end_day").datetimepicker();

//  $(".datepicker").datepicker(
//     {
//         dateFormat: "yy-mm-dd",
//         changeYear:true,
//         changeMonth:true,
//   }
//  )

} );
</script>

{% endblock javascripts %}

templates/borrow_records/detail.html
{% extends "layouts/base.html" %}
{% load book_extras %}
{% block title %} 管理 {% endblock %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="page-header">
            <div class="page-block">
                <!-- Title -->
                <div class="row align-items-center">
                    <!-- <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10"><span><i class="fas fa-user "></i> {{record.borrower}} => "{{record.book}}"  </span></h5>
                        </div>
                    </div> -->
                </div>
            </div>

        </div>

        <br>
        <!-- [ breadcrumb ] end -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <!-- [ basic-table ] start -->
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="m-b-10"><span><i class="fas fa-user "></i> {{record.borrower}} => "{{record.book}}"  </span></h5>
                            </div>
                            
                            {% show_messages %}

                            <div class="card-block ">
                                <div class='row'>
                                    <div class="col-12 d-flex justify-content-center text-center">
                                        <table class="table table-sm  ">
                                            <thead class="thead-dark">
                                              <tr>
                                                <th scope="col">字段属性</th>
                                                <th scope="col">值</th>
                                  
                                              </tr>
                                            </thead>
                                            <tbody>
                                              
                                                <tr>
                                                    <td>租借用户名称</td>
                                                    <td>{{record.borrower}}</td>                                                
                                                </tr>
                                                <tr>
                                                    <td>用户卡号</td>
                                                    <td>{{record.borrower_card}}</td>                                                
                                                </tr>
                                                <tr>
                                                    <td>用户联系方式</td>
                                                    <td>{{record.borrower_email}} / {{record.borrower_phone_number}}</td>                                                
                                                </tr>
                                                <tr>
                                                    <td>租借物品名称</td>
                                                    <td>{{record.book}}</td>                                                
                                                </tr>
                                                <tr>
                                                    <td>物品数量</td>
                                                    <td>{{record.quantity}}</td>                                                
                                                </tr>
                                     
                                                <tr>
                                                    <td>租借时间</td>
                                                    <td>{{record.start_day| date:"Y-m-d"}}起{{record.end_day| date:"Y-m-d"}}止, 共计{{record.periode}}天 </td>
                                                </tr>

                                                
                                                <tr>
                                                    <td>是否预期? </td>
                                                    {% if record.return_status == "On time"%}
                                                    <td>{{record.return_status}}</td>
                                                    {% else %}
                                                    <td>{{record.return_status}}, 延期 {{record.get_delay_number_days}} 天 </td>
                                                    {% endif %}
                                                </tr>

                                                <tr>
                                                    <td>记录状态 </td>
                                                    <td>{{record.get_open_or_close_display}}</td>                                                
                                                </tr>

                                                <tr>
                                                    <td>处理者</td>
                                                    <td>{{record.closed_by}}</td>                                                
                                                </tr>

                                                <tr>
                                                    <td>归还于</td>
                                                    <td>{{record.closed_at| date:"Y-m-d H:i"}}</td>                                                
                                                </tr>
                                            </tbody>
                                          </table>                    
                                    </div>
                                </div>

                                <a href="{% url 'record_list' %}" class='btn btn-primary'>返回</a>

                                {% if record.open_or_close == 0 %}

                                <a href="{% url 'record_close' record.pk %}" class='btn btn-danger'>归还物品</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    
                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/borrow_records/list.html
{% extends "layouts/base.html" %}
{% load book_extras %}

{% block title %} Borrow Records {% endblock %} }
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">所有租借记录</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <br>
        <div class="main-body">
            <div class="page-wrapper">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-header">
                                <h5> 总共{{count_total}}条记录 </h5>
                            </div>
                            {% show_messages %}

                            <div class="card-block ">
                                <div class='row'>
                                    <div class="col-8">
                                        <b>请选择排序方式 : - </b>
                                        <a href="{% url 'record_list' %}?search={{search}}&orderby=id">Id</a>  | 
                                        <a href="{% url 'record_list' %}?search={{ search }}&orderby=borrower">用户名字</a> |
                                        <a href="{% url 'record_list' %}?search={{ search }}&orderby=book">物品名</a> |
                                        <a href="{% url 'record_list' %}?search={{ search }}&orderby=start_day">租借日期</a> |
                                        <a href="{% url 'record_list' %}?search={{ search }}&orderby=end_day">归还日期</a>|
                                        <a href="{% url 'record_list' %}?search={{ search }}&orderby=closed_at">Closed date</a> |
                                        
                                    </div>
                                    <div class="col-auto">
                                        <form class="form-inline mb-2">
                                            <div class="form-group  mb-2">
                                                <input type="text" 
                                                       class="form-control" 
                                                       name="search",
                                                       id='search',
                                                       placeholder="搜索姓名或者卡号",
                                                       value={{search}}
                                                       >
                                            </div>
                                            <button type="submit" class="btn btn-secondary mb-2 ml-1 btn-sm">搜索一下</button>
                                        </form>
                                    </div>
                                </div>

                                <div class="table-responsive table-hover">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>姓名</th>
                                                <th>卡号</th>
                                                <th>手机号</th>
                                                <th>物品</th>
                                                <th>数量</th>
                                                <th>租借日期</th>
                                                <th>归还日期</th>
                                                <th>物品状态</th>
                                                <th>超时情况</th>
                                                <th>#</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for record in records %}
                                            <tr>
                                                <td>{{record.borrower}}</td>  
                                                <td>{{record.borrower_card}}</td>  
                                                <td>{{record.borrower_phone_number}}</a></td>   
                                                <td>{{record.book|truncatewords:2}}</td>
                                                <td>{{record.quantity}}</td>
                                                <td>{{record.start_day|date:"Y-m-d"}}</td>
                                                <td>{{record.end_day|date:"Y-m-d"}}</td>
                                                <td>{{record.get_open_or_close_display}}</td>
                                                {% if record.return_status == "Delayed" %}
                                                <td class='table-danger'>{{record.return_status}} {{record.get_delay_number_days}} days</td>
                                                {% else %}
                                                <td class='table-success'>{{record.return_status}}</td>
                                                {% endif %}
                                                <td>
                                                    <a href="{% url 'record_detail' record.pk %}" class="badge badge-warning badge-bg"><i class="feather icon-eye"></i>&nbsp;检查</a>

                                                    <a href="{% url 'record_delete' record.pk %}" class="badge badge-danger"><i class="feather icon-trash-2"></i>&nbsp;删除</a>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                                <div class="row">
                                    <div class='col-6'>
                                        <a href="{% url 'record_create' %}" class='btn btn-primary'>增加新的记录</a>
                                    </div>
                                    <div class='col-6'>
                                        {% show_pagination %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascripts %}{% endblock javascripts %}